[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap [nerdtree] <nop>
  nmap <Space>n [nerdtree]
  nnoremap <silent>[nerdtree]n :NERDTreeToggle<CR>
  nnoremap <silent>[nerdTree]f :NERDTreeFind<CR>
'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'vim-scripts/vim-auto-save'
# hook_add = 'let g:auto_save = 1'

