[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap [nerdtree] <nop>
  nmap <Space>n [nerdtree]
  nnoremap <silent>[nerdtree]n :NERDTreeToggle<CR>
  nnoremap <silent>[nerdTree]f :NERDTreeFind<CR>
'''

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  nmap s <Plug>(easymotion-s2)
  xmap s <Plug>(easymotion-s2)
  map / <Plug>(easymotion-sn)
  omap / <Plug>(easymotion-tn)
  map <Leader>l <Plug>(easymotion-bd-jk)
  nmap <Leader>l <Plug>(easymotion-overwin-line)
  let g:EasyMotion_keys = 'QZASDFGHJKL;'
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_startofline = 0
  let g:EasyMotion_use_upper = 1
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
  hi EasyMotionTarget guifg=#80a0ff ctermfg=81
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# [[plugins]]
# repo = 'vim-scripts/vim-auto-save'
# hook_add = 'let g:auto_save = 1'

