[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'
